-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 12:38:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Клиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Клиенты` (   
    `id_Клиенты` INT NOT NULL AUTO_INCREMENT,   
    `фамилия` VARCHAR(50) NOT NULL,   
    `имя` VARCHAR(50) NOT NULL,   
    `отчество` VARCHAR(50) NULL,   
    `телефон` VARCHAR(20) NULL,   
    `дата_рождения` DATE NULL,   
    `email` VARCHAR(100) NULL,   
    PRIMARY KEY (`id_Клиенты`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Абонементы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Абонементы` (   
    `id_абонемента` INT NOT NULL AUTO_INCREMENT,   
    `тип` VARCHAR(50) NOT NULL,   
    `срок_дней` INT NOT NULL,   
    `цена` DECIMAL(10,2) NOT NULL,   
    `количество_посещений` INT NULL,   
    PRIMARY KEY (`id_абонемента`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Покупка_абонемента`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Покупка_абонемента` (   
    `id_покупки` INT NOT NULL AUTO_INCREMENT,   
    `дата_покупки` DATE NOT NULL,   
    `дата_активации` DATE NULL,   
    `дата_окончания` DATE NULL,   
    `id_клиента` INT NOT NULL,   
    `id_абонемента` INT NOT NULL,   
    PRIMARY KEY (`id_покупки`),   
    INDEX `Клиенты_idx` (`id_клиента` ASC) VISIBLE,   
    INDEX `Абонементы_idx` (`id_абонемента` ASC) VISIBLE,   
    CONSTRAINT `Клиенты`     
        FOREIGN KEY (`id_клиента`)     
        REFERENCES `mydb`.`Клиенты` (`id_Клиенты`)     
        ON DELETE CASCADE     
        ON UPDATE CASCADE,   
    CONSTRAINT `Абонементы`     
        FOREIGN KEY (`id_абонемента`)     
        REFERENCES `mydb`.`Абонементы` (`id_абонемента`)     
        ON DELETE NO ACTION     
        ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Тренировки`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Тренировки`;

CREATE TABLE IF NOT EXISTS `mydb`.`Тренировки` (   
    `id_тренировки` INT NOT NULL AUTO_INCREMENT,   
    `название` VARCHAR(100) NOT NULL,   
    `тренер` VARCHAR(100) NULL,   
    `макс_участников` INT NULL,   
    PRIMARY KEY (`id_тренировки`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Запись_на_тренировку`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Запись_на_тренировку` (   
    `id_записи` INT NOT NULL AUTO_INCREMENT,   
    `дата` DATE NOT NULL,   
    `время` TIME NOT NULL,   
    `статус` VARCHAR(20) NULL,   
    `id_клиента` INT NOT NULL,   
    `id_тренировки` INT NOT NULL,   
    PRIMARY KEY (`id_записи`),   
    INDEX `Клиенты_idx` (`id_клиента` ASC) VISIBLE,   
    INDEX `Тренировки_idx` (`id_тренировки` ASC) VISIBLE,   
    CONSTRAINT `fk_запись_клиент`     
        FOREIGN KEY (`id_клиента`)     
        REFERENCES `mydb`.`Клиенты` (`id_Клиенты`)     
        ON DELETE CASCADE     
        ON UPDATE CASCADE,   
    CONSTRAINT `fk_запись_тренировка`     
        FOREIGN KEY (`id_тренировки`)     
        REFERENCES `mydb`.`Тренировки` (`id_тренировки`)     
        ON DELETE CASCADE     
        ON UPDATE CASCADE
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`Посещения`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Посещения` (   
    `id_посещения` INT NOT NULL AUTO_INCREMENT,   
    `дата` DATE NOT NULL,   
    `время` TIME NOT NULL,   
    `id_клиента` INT NOT NULL,   
    `id_тренировки` INT NOT NULL,   
    PRIMARY KEY (`id_посещения`),   
    INDEX `Клиенты_idx` (`id_клиента` ASC) VISIBLE,   
    INDEX `Тренировки_idx` (`id_тренировки` ASC) VISIBLE,   
    CONSTRAINT `fk_посещение_клиент`     
        FOREIGN KEY (`id_клиента`)     
        REFERENCES `mydb`.`Клиенты` (`id_Клиенты`)     
        ON DELETE CASCADE     
        ON UPDATE CASCADE,   
    CONSTRAINT `fk_посещение_тренировка`     
        FOREIGN KEY (`id_тренировки`)     
        REFERENCES `mydb`.`Тренировки` (`id_тренировки`)     
        ON DELETE CASCADE     
        ON UPDATE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
